# Dyatel configuration parameters definition file.
# It is used (ok, it should be used) for at least 2 purposes: Configuration
# editor page building and poor man's internal documentation.
---
- section: route
  params:
    - name: debug
      type: boolean
      defval: false
      descr: Store call.route parameters and resulting decision in call's log.
    - name: schedule_override
      type: string
      defval: null
      descr: Override calculated (day/night) routing mode.
- section: ui
  params:
    - name: language
      type: string
      defval: en
      descr: User interface language


