# Dyatel configuration parameters definition file.
# It is used (ok, it should be used) for at least 2 purposes: Configuration
# editor page building and poor man's internal documentation.

# Parameter's type should be one of [ string, boolean, select ]
# If type is 'select', additional key 'options' should be added
# with array of valid values. If 'opptions' is a string of form
# 'DB::Table.field', options list will be loaded from given
# database table.
---
- section: route
  params:
    - name: debug
      type: boolean
      defval: false
      descr: Store call.route parameters and resulting decision in call's log.
    - name: schedule_override
      type: select
      options: 'DB::Incoming.mode'
      defval: null
      descr: Override calculated (day/night) routing mode.
- section: ui
  params:
    - name: language
      type: select
      options: [ en, ru ]
      defval: en
      descr: User interface language
    - name: debug
      type: boolean
      defval: false
      descr: Show developer's user interface elements

# vim: ts=2 sw=2 sts=2 et

